name: Publish Github Release with jDeploy

on:
  push:
    branches: [ 'main' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'liberica'
          cache: maven

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: gradlew assemble
      - name: Publish Master Branch with jDeploy
        uses: shannah/jdeploy@master
        with:
          github_token: '${{ secrets.JDeploy }}'
